Shepherd typos
anima-wg/brski-cloud pull request #88
Opened 2023-12-18 23:00 UTC by mcr

2024-01-04 12:23 UTC, upros commented on anima-brski-cloud.md
> +If the est-domain was provided by with an IP address literal, then it is unlikely that it can be validated, and in that case, it is expected that either a self-signed certificate r an EE certificate
typo: "a self-signed certificate r an EE certificate"

Change "r an EE" to "or an EE"

2024-01-04 12:24 UTC, upros commented on anima-brski-cloud.md
> +The Cloud Registrar does not have a have a certificate that can be validated using a public (WebPKI) anchor.
Typo: "have a have a"

You said "have a" twice!

2024-01-04 12:25 UTC, upros requested changes
I called out two minor nits.

2024-01-04 21:52 UTC, mcr commented on anima-brski-cloud.md
> +If the est-domain was provided by with an IP address literal, then it is unlikely that it can be validated, and in that case, it is expected that either a self-signed certificate r an EE certificate
```suggestion
If the est-domain was provided by with an IP address literal, then it is unlikely that it can be validated, and in that case, it is expected that either a self-signed certificate or an EE certificate will be pinned by the voucher.
```

2024-01-04 21:53 UTC, mcr commented on anima-brski-cloud.md
> +The Cloud Registrar does not have a have a certificate that can be validated using a public (WebPKI) anchor.
```suggestion
The Cloud Registrar does not have a certificate that can be validated using a public (WebPKI) anchor.
```

2024-01-08 10:02 UTC, upros approved these changes

2024-01-08 10:02 UTC, merged