Intro fixes
anima-wg/brski-cloud pull request #89
Opened 2024-01-02 13:54 UTC by mcr

close #49

2024-01-04 12:27 UTC, upros commented on anima-brski-cloud.md
> +The pledge does not know who its owner will be when manufacturer.
Typo: "when manufacturer." should be " when manufactured."

2024-01-04 12:29 UTC, upros commented on anima-brski-cloud.md
> +THis work is in support of {{BRSKI, Section 2.7}}, which describes how a pledge "MAY contact a well-known URI of a Cloud Registrar if a local Registrar cannot be discovered or if the pledge's target
Typo: "THis" should be "this"

2024-01-04 12:29 UTC, upros requested changes
Identified two minor nits.

2024-01-04 21:53 UTC, mcr commented on anima-brski-cloud.md
> +The pledge does not know who its owner will be when manufacturer.
```suggestion
The pledge does not know who its owner will be when manufactured.
```

2024-01-04 21:54 UTC, mcr commented on anima-brski-cloud.md
> +THis work is in support of {{BRSKI, Section 2.7}}, which describes how a pledge "MAY contact a well-known URI of a Cloud Registrar if a local Registrar cannot be discovered or if the pledge's target
```suggestion
This work is in support of {{BRSKI, Section 2.7}}, which describes how a pledge "MAY contact a well-known URI of a Cloud Registrar if a local Registrar cannot be discovered or if the pledge's target use cases do not include a local Registrar".
```

2024-01-08 10:02 UTC, upros approved these changes

2024-01-08 10:02 UTC, merged